[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda-dist"
[build.environment]
  NODE_VERSION = "15"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  baseUrl = "https://__template__website__name.com/"
  sitemapPath = "/sitemap.xml"
  providers = [
    "google",
    "bing",
    "yandex"
  ]
